// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alsmnxnairmwgrwylhep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsc21ueG5haXJtd2dyd3lsaGVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NDMxNjIsImV4cCI6MjA3MjUxOTE2Mn0.XpwaUnZQ0ZavbZRkOONA4C0MDG6oiDEoXWotyp5xi9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});